apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: asia-southeast1-docker.pkg.dev/inari-poc/inari-poc-registry/test-argo
    newName: asia-southeast1-docker.pkg.dev/inari-poc/inari-poc-registry/test-argo
    newTag: latest

patchesStrategicMerge:
  - set_resources.yaml

configMapGenerator:
  - name: test-argo
    envs:
      - config.env

secretGenerator:
  - name: test-argo
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true
