apiVersion: v1
kind: Service
metadata:
  name: test-argo
  labels:
    app.kubernetes.io/name: test-argo
    app.kubernetes.io/instance: test-argo
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: test-argo
    app.kubernetes.io/instance: test-argo
